### ISSUE TITLE
Cannot find module 'httpp'

### ISSUE THREAD

**Issue by EverettQuebral** [InstantWebP2P/node-httpp-proxy#4]
Followed your instruction to install httpp-proxy

cis-fe equebral$ npm install httpp-proxy --save
npm WARN package.json cis-fe@0.1.0 No repository field.
httpp-proxy@0.10.3 node_modules/httpp-proxy
├── colors@0.6.2
├── pkginfo@0.2.3
├── optimist@0.3.7 (wordwrap@0.0.3)
└── utile@0.1.7 (deep-equal@1.0.0, rimraf@1.0.9, ncp@0.2.7, async@0.1.22, i@0.3.3, mkdirp@0.5.1)
LM-SJN-00716137:cis-fe equebral$ npm start

on the code
var http = require('http');
var httpProxy = require('http-proxy');

get's this error
> cis-fe@0.1.0 start /Users/equebral/projects/cis-fe
> node server.js

Wed, 17 Jun 2015 23:04:43 GMT uncaughtException Cannot find module 'http-proxy'
Error: Cannot find module 'http-proxy'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/equebral/projects/cis-fe/server.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

if I change to require('httpp-proxy');

Wed, 17 Jun 2015 23:07:01 GMT uncaughtException Cannot find module 'httpp'
Error: Cannot find module 'httpp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/equebral/projects/cis-fe/node_modules/httpp-proxy/lib/node-http-proxy.js:30:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Xrave** [comment]
Got same error. Something weird is going on with this where it requires the httpp module inside node-httpp-proxy, except that dependency is unlisted and also doesn't compile in my env (node 0.12.6)

**Comment by sequoiar** [comment]
node-httpp-proxy rely on node-httpp, which is fork of nodejs v0.8
https://github.com/InstantWebP2P/node-httpp
